import { db } from '@/lib/db'
import Link from 'next/link'
import { ArrowUpRight, Check } from 'lucide-react'
import { buildMetadata } from '@/lib/seo'

export const metadata = buildMetadata({ title: 'Software Development Pricing & Packages | Unifex Solutions', description: 'Explore transparent Unifex engagement packages for websites, software products, cybersecurity, and digital growth.', path: '/pricing' })
export const revalidate = 60

export default async function PricingPage() {
  const packages = await db.pricingPackage.findMany({ where: { published: true }, orderBy: { displayOrder: 'asc' } })
  return <main className="min-h-screen overflow-hidden bg-background pt-24 text-on-surface"><section className="container mx-auto px-6 py-32 md:px-12 md:py-48"><p className="mb-10 text-[10px] font-black uppercase tracking-[0.6em] text-primary">Registry // Investment structures</p><h1 className="font-headline text-6xl font-black uppercase leading-[0.82] tracking-[-0.08em] md:text-9xl">Choose your<br /><span className="text-on-surface/25">foundation.</span></h1><p className="mt-14 max-w-3xl border-l-4 border-primary/30 pl-8 text-lg uppercase leading-relaxed text-on-surface/65">Clear engagement packages for ambitious digital products. Every scope is shaped around the system you actually need.</p></section><section className="container mx-auto px-6 pb-32 md:px-12">{packages.length === 0 ? <div className="border border-outline-variant/20 p-16 text-center text-xs font-black uppercase tracking-[0.3em] text-on-surface/40">Contact us for a custom proposal.</div> : <div className="grid gap-px bg-outline-variant/15 md:grid-cols-3">{packages.map((tier) => { let features: string[] = []; try { const parsed = JSON.parse(tier.features || '[]'); features = Array.isArray(parsed) ? parsed.filter(Boolean) : [] } catch {} return <article key={tier.id} className={`bg-surface p-8 md:p-12 ${tier.popular ? 'border-t-4 border-primary' : ''}`}><p className="mb-5 text-[10px] font-black uppercase tracking-[0.4em] text-primary">{tier.popular ? 'Recommended' : 'Engagement tier'}</p><h2 className="font-headline text-4xl font-black uppercase">{tier.name}</h2><p className="mt-5 font-headline text-3xl font-black text-primary">{tier.price} <span className="text-xs text-on-surface/40">{tier.currency}</span></p><p className="mt-8 min-h-16 text-sm leading-relaxed text-on-surface/55">{tier.description}</p><div className="mt-10 space-y-4">{features.map((feature) => <p key={feature} className="flex gap-3 text-xs uppercase text-on-surface/75"><Check className="h-4 w-4 shrink-0 text-primary" />{feature}</p>)}</div><Link href="/contact" className="mt-12 flex items-center justify-between bg-primary px-5 py-4 text-[10px] font-black uppercase tracking-[0.25em] text-black">Discuss this tier <ArrowUpRight className="h-4 w-4" /></Link></article>})}</div>}</section></main>
}
